# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190317_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.FileField(upload_to='static/songs'),
        ),
    ]
