# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190318_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.FileField(upload_to='songs'),
        ),
    ]
